export type SeedCategory = {
  name: string
  type: 'fixed' | 'variable' | 'income' | 'transfer'
  color: string
  icon: string
  is_system: boolean
}

export type SeedRule = {
  categoryKey: string
  match_field: 'recipient' | 'sender' | 'subject' | 'any'
  match_value: string
  match_type: 'contains' | 'exact' | 'startswith'
  priority: number
}

export const SEED_CATEGORIES: SeedCategory[] = [
  // Fixed
  { name: 'Miete & Wohnen', type: 'fixed', color: '#6366f1', icon: 'Home', is_system: true },
  { name: 'Versicherungen', type: 'fixed', color: '#f59e0b', icon: 'Shield', is_system: true },
  { name: 'Telefon & Internet', type: 'fixed', color: '#0ea5e9', icon: 'Wifi', is_system: true },
  { name: 'Strom & Gas', type: 'fixed', color: '#f97316', icon: 'Zap', is_system: true },
  { name: 'Streaming & Abos', type: 'fixed', color: '#8b5cf6', icon: 'Play', is_system: true },
  { name: 'GEZ / Rundfunk', type: 'fixed', color: '#64748b', icon: 'Radio', is_system: true },
  { name: 'Kreditraten', type: 'fixed', color: '#ef4444', icon: 'CreditCard', is_system: true },
  { name: 'Mitgliedschaften', type: 'fixed', color: '#10b981', icon: 'Star', is_system: true },
  // Variable
  { name: 'Lebensmittel', type: 'variable', color: '#22c55e', icon: 'ShoppingCart', is_system: true },
  { name: 'Drogerie & Körperpflege', type: 'variable', color: '#06b6d4', icon: 'Sparkles', is_system: true },
  { name: 'Restaurants & Cafés', type: 'variable', color: '#fb923c', icon: 'UtensilsCrossed', is_system: true },
  { name: 'Transport & Mobilität', type: 'variable', color: '#3b82f6', icon: 'Car', is_system: true },
  { name: 'Shopping & Kleidung', type: 'variable', color: '#ec4899', icon: 'ShoppingBag', is_system: true },
  { name: 'Gesundheit & Apotheke', type: 'variable', color: '#14b8a6', icon: 'Heart', is_system: true },
  { name: 'Freizeit & Sport', type: 'variable', color: '#a855f7', icon: 'Dumbbell', is_system: true },
  { name: 'Reisen & Urlaub', type: 'variable', color: '#06b6d4', icon: 'Plane', is_system: true },
  { name: 'Bildung', type: 'variable', color: '#f59e0b', icon: 'BookOpen', is_system: true },
  { name: 'Haushalt & Reparaturen', type: 'variable', color: '#84cc16', icon: 'Wrench', is_system: true },
  { name: 'Geschenke & Spenden', type: 'variable', color: '#e11d48', icon: 'Gift', is_system: true },
  { name: 'Sonstiges', type: 'variable', color: '#94a3b8', icon: 'MoreHorizontal', is_system: true },
  // Income
  { name: 'Gehalt', type: 'income', color: '#22c55e', icon: 'Banknote', is_system: true },
  { name: 'Freiberuflich', type: 'income', color: '#10b981', icon: 'Briefcase', is_system: true },
  { name: 'Sonstige Einnahmen', type: 'income', color: '#6366f1', icon: 'TrendingUp', is_system: true },
  // Transfer
  { name: 'Umbuchungen', type: 'transfer', color: '#94a3b8', icon: 'ArrowLeftRight', is_system: true },
]

export const SEED_RULES: SeedRule[] = [
  // ── Lebensmittel ─────────────────────────────────────────
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'REWE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'EDEKA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'LIDL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'ALDI', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'PENNY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'NETTO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'KAUFLAND', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'NORMA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'TEGUT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'REAL MARKT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'HIT MARKT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'GLOBUS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'FAMILA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'COMBI', match_type: 'contains', priority: 5 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'SPAR MARKT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'NAHKAUF', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'BILLA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'VOLLCORNER', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'DENN\'S BIO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Lebensmittel', match_field: 'any', match_value: 'BIO COMPANY', match_type: 'contains', priority: 10 },

  // ── Drogerie & Körperpflege ──────────────────────────────
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'DM-DROGERIE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'DM DROGERIE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'ROSSMANN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'MUELLER DROGERIE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'MÜLLER DROGERIE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'BUDNI', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'DOUGLAS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'BODYSHOP', match_type: 'contains', priority: 10 },
  { categoryKey: 'Drogerie & Körperpflege', match_field: 'any', match_value: 'THE BODY SHOP', match_type: 'contains', priority: 10 },

  // ── Restaurants & Cafés ─────────────────────────────────
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'MCDONALDS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'MC DONALD', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'BURGER KING', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'SUBWAY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'KFC', match_type: 'contains', priority: 8 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'DOMINOS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'DOMINO\'S', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'PIZZA HUT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'LIEFERANDO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'UBER EATS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'UBEREATS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'DELIVEROO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'WOLT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'STARBUCKS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'VAPIANO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'NORDSEE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'BACKWERK', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'BAECKER', match_type: 'contains', priority: 5 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'BÄCKER', match_type: 'contains', priority: 5 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'BACKHAUS', match_type: 'contains', priority: 5 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'KAMPS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'YORMAS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Restaurants & Cafés', match_field: 'any', match_value: 'DUNKIN', match_type: 'contains', priority: 10 },

  // ── Transport & Mobilität ────────────────────────────────
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'DEUTSCHE BAHN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'DB BAHN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'DB FERNVERKEHR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'FLIXBUS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'FLIXTRAIN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'BVG', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'MVV', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'HVV', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'RMV', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'VVS', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'MVG', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'NAHVERKEHR', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'SIXT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'HERTZ', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'EUROPCAR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'ENTERPRISE', match_type: 'contains', priority: 5 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'TIER MOBILITY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'LIME', match_type: 'contains', priority: 5 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'BOLT.EU', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'NEXTBIKE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'FLINKSTER', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'SHARE NOW', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'MILES MOBILITY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'FREE NOW', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'TAXI', match_type: 'contains', priority: 5 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'UBER', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'TANKSTELLE', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'ARAL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'SHELL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'ESSO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'TOTAL TANKSTELLE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'JET TANKSTELLE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'AUTOBAHN TANK', match_type: 'contains', priority: 10 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'AUTOPFLEGE', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'PARKHAUS', match_type: 'contains', priority: 8 },
  { categoryKey: 'Transport & Mobilität', match_field: 'any', match_value: 'PARKGEBUEHR', match_type: 'contains', priority: 8 },

  // ── Streaming & Abos ────────────────────────────────────
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'NETFLIX', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'SPOTIFY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'APPLE.COM/BILL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'APPLE SUBSCR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'ITUNES', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'DISNEY PLUS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'DISNEY+', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'DAZN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'AMAZON PRIME', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'YOUTUBE PREMIUM', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'AUDIBLE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'KINDLE UNLIMITED', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'MICROSOFT 365', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'OFFICE 365', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'ADOBE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'MAGENTA TV', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'WOW STREAMING', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'JOYN', match_type: 'contains', priority: 8 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'SKY TICKET', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'SKY DEUTSCHLAND', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'AMAZON PAYMENTS', match_type: 'contains', priority: 8 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'GOOGLE STORAGE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'ICLOUD', match_type: 'contains', priority: 10 },
  { categoryKey: 'Streaming & Abos', match_field: 'any', match_value: 'DROPBOX', match_type: 'contains', priority: 10 },

  // ── Telefon & Internet ───────────────────────────────────
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'DEUTSCHE TELEKOM', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'TELEKOM DEUTSCHLAND', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'VODAFONE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'O2 ONLINE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'TELEFONICA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: '1&1 INTERNET', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: '1UND1', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'FREENET', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'CONGSTAR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'SIMYO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'KLARMOBIL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'MOBILCOM', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'DEBITEL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'KABEL DEUTSCHLAND', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'UNITYMEDIA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Telefon & Internet', match_field: 'any', match_value: 'INTERNET SERVICE', match_type: 'contains', priority: 5 },

  // ── Strom & Gas ─────────────────────────────────────────
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'E.ON', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'EON ENERGIE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'RWE', match_type: 'contains', priority: 8 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'VATTENFALL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'ENBW', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'INNOGY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'STADTWERKE', match_type: 'contains', priority: 8 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'TIBBER', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'AWATTAR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'GREENPEACE ENERGY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'NATURSTROM', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'STROM ABSCHLAG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'GAS ABSCHLAG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Strom & Gas', match_field: 'any', match_value: 'ENERGIE ABSCHLAG', match_type: 'contains', priority: 10 },

  // ── Versicherungen ───────────────────────────────────────
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'ALLIANZ', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'AXA VERSICHERUNG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'ERGO', match_type: 'contains', priority: 8 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'HUK-COBURG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'HUK COBURG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'GENERALI', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'R+V VERSICHERUNG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'ZURICH', match_type: 'contains', priority: 8 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'SIGNAL IDUNA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'LVM VERSICHERUNG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'VHV VERSICHERUNG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'DEVK', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'GOTHAER', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'BARMENIA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'WUERTTEMBERG', match_type: 'contains', priority: 8 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'WÜRTTEMBERGISCHE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'VERSICHERUNG BEITRAG', match_type: 'contains', priority: 8 },
  { categoryKey: 'Versicherungen', match_field: 'any', match_value: 'PRÄMIE', match_type: 'contains', priority: 5 },

  // ── GEZ / Rundfunk ───────────────────────────────────────
  { categoryKey: 'GEZ / Rundfunk', match_field: 'any', match_value: 'ARD ZDF DEUTSCHLANDRADIO', match_type: 'contains', priority: 10 },
  { categoryKey: 'GEZ / Rundfunk', match_field: 'any', match_value: 'RUNDFUNKBEITRAG', match_type: 'contains', priority: 10 },
  { categoryKey: 'GEZ / Rundfunk', match_field: 'any', match_value: 'GEZ', match_type: 'contains', priority: 10 },
  { categoryKey: 'GEZ / Rundfunk', match_field: 'any', match_value: 'BEITRAGSSERVICE', match_type: 'contains', priority: 10 },

  // ── Shopping & Kleidung ──────────────────────────────────
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'AMAZON.DE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'AMAZON MKTPLACE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'ZALANDO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'OTTO GMBH', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'OTTO.DE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'ABOUT YOU', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'H&M', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'ZARA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'C&A', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'PRIMARK', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'TK MAXX', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'PEEK CLOPPENBURG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'SOLIVER', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'EBAY', match_type: 'contains', priority: 8 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'PAYPAL', match_type: 'contains', priority: 3 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'SHEIN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'TEMU', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'BONPRIX', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'ESPRIT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'TOMMY HILFIGER', match_type: 'contains', priority: 10 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'NIKE', match_type: 'contains', priority: 8 },
  { categoryKey: 'Shopping & Kleidung', match_field: 'any', match_value: 'ADIDAS', match_type: 'contains', priority: 10 },

  // ── Gesundheit & Apotheke ────────────────────────────────
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'APOTHEKE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'PHARMACY', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'AOK', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'TECHNIKER KRANKENKASSE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'BARMER', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'DAK GESUNDHEIT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'IKK', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'KRANKENKASSE', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'ARZTPRAXIS', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'ZAHNARZT', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'KRANKENHAUS', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'KLINIK', match_type: 'contains', priority: 8 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'DOCMORRIS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gesundheit & Apotheke', match_field: 'any', match_value: 'SHOP APOTHEKE', match_type: 'contains', priority: 10 },

  // ── Freizeit & Sport ─────────────────────────────────────
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'MCFIT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'FITX', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'FITNESS FIRST', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'FITNESSSTUDIO', match_type: 'contains', priority: 8 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'SPORTSTUDIO', match_type: 'contains', priority: 8 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'DECATHLON', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'INTERSPORT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'SPORT SCHECK', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'STEAM', match_type: 'contains', priority: 8 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'XBOX', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'PLAYSTATION', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'NINTENDO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'KINO', match_type: 'contains', priority: 8 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'CINEMAXX', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'UCI KINOWELT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Freizeit & Sport', match_field: 'any', match_value: 'THEATER', match_type: 'contains', priority: 5 },

  // ── Reisen & Urlaub ──────────────────────────────────────
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'LUFTHANSA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'EUROWINGS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'RYANAIR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'EASYJET', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'WIZZ AIR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'CONDOR', match_type: 'contains', priority: 8 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'BOOKING.COM', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'AIRBNB', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'HOTELS.COM', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'EXPEDIA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Reisen & Urlaub', match_field: 'any', match_value: 'CHECK24 REISE', match_type: 'contains', priority: 10 },

  // ── Bildung ──────────────────────────────────────────────
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'UDEMY', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'COURSERA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'SKILLSHARE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'DUOLINGO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'THALIA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'HUGENDUBEL', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'WELTBILD', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'VOLKSHOCHSCHULE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'STUDIENGEBUEHR', match_type: 'contains', priority: 10 },
  { categoryKey: 'Bildung', match_field: 'any', match_value: 'SEMESTERGEBUEHR', match_type: 'contains', priority: 10 },

  // ── Haushalt & Reparaturen ───────────────────────────────
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'IKEA', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'BAUHAUS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'OBI', match_type: 'contains', priority: 8 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'HORNBACH', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'TOOM BAUMARKT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'SATURN', match_type: 'contains', priority: 8 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'MEDIAMARKT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'MEDIA MARKT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'EXPERT ELEKTRO', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'EURONICS', match_type: 'contains', priority: 10 },
  { categoryKey: 'Haushalt & Reparaturen', match_field: 'any', match_value: 'CONRAD', match_type: 'contains', priority: 8 },

  // ── Gehalt / Einnahmen ───────────────────────────────────
  { categoryKey: 'Gehalt', match_field: 'subject', match_value: 'GEHALT', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gehalt', match_field: 'subject', match_value: 'LOHN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gehalt', match_field: 'subject', match_value: 'BEZÜGE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gehalt', match_field: 'subject', match_value: 'BEZUEGE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Gehalt', match_field: 'subject', match_value: 'DIENSTBEZUEGE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'RENTE', match_type: 'contains', priority: 8 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'PENSION', match_type: 'contains', priority: 8 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'KINDERGELD', match_type: 'contains', priority: 10 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'ELTERNGELD', match_type: 'contains', priority: 10 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'ERSTATTUNG', match_type: 'contains', priority: 5 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'RUECKZAHLUNG', match_type: 'contains', priority: 5 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'RÜCKZAHLUNG', match_type: 'contains', priority: 5 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'STEUERERSTATTUNG', match_type: 'contains', priority: 10 },
  { categoryKey: 'Sonstige Einnahmen', match_field: 'subject', match_value: 'ZINSEN', match_type: 'contains', priority: 8 },

  // ── Umbuchungen ──────────────────────────────────────────
  { categoryKey: 'Umbuchungen', match_field: 'subject', match_value: 'UMBUCHUNG', match_type: 'contains', priority: 15 },
  { categoryKey: 'Umbuchungen', match_field: 'subject', match_value: 'ÜBERTRAG', match_type: 'contains', priority: 15 },
  { categoryKey: 'Umbuchungen', match_field: 'subject', match_value: 'UEBERTRAG', match_type: 'contains', priority: 15 },
  { categoryKey: 'Umbuchungen', match_field: 'subject', match_value: 'EIGENE BUCHUNG', match_type: 'contains', priority: 15 },
  { categoryKey: 'Umbuchungen', match_field: 'subject', match_value: 'SPAREN', match_type: 'contains', priority: 8 },
  { categoryKey: 'Umbuchungen', match_field: 'subject', match_value: 'SPARPLAN', match_type: 'contains', priority: 10 },
  { categoryKey: 'Umbuchungen', match_field: 'subject', match_value: 'DEPOTBUCHUNG', match_type: 'contains', priority: 10 },

  // ── Miete & Wohnen ───────────────────────────────────────
  { categoryKey: 'Miete & Wohnen', match_field: 'subject', match_value: 'MIETE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Miete & Wohnen', match_field: 'subject', match_value: 'KALTMIETE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Miete & Wohnen', match_field: 'subject', match_value: 'WARMMIETE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Miete & Wohnen', match_field: 'subject', match_value: 'NEBENKOSTEN', match_type: 'contains', priority: 8 },
  { categoryKey: 'Miete & Wohnen', match_field: 'subject', match_value: 'HAUSGELD', match_type: 'contains', priority: 10 },
  { categoryKey: 'Miete & Wohnen', match_field: 'subject', match_value: 'WOHNUNGSMIETE', match_type: 'contains', priority: 10 },
  { categoryKey: 'Miete & Wohnen', match_field: 'subject', match_value: 'WOHNGELD', match_type: 'contains', priority: 10 },

  // ── Mitgliedschaften ─────────────────────────────────────
  { categoryKey: 'Mitgliedschaften', match_field: 'any', match_value: 'ADAC', match_type: 'contains', priority: 10 },
  { categoryKey: 'Mitgliedschaften', match_field: 'any', match_value: 'GEWERKSCHAFT', match_type: 'contains', priority: 8 },
  { categoryKey: 'Mitgliedschaften', match_field: 'any', match_value: 'VEREIN BEITRAG', match_type: 'contains', priority: 8 },
  { categoryKey: 'Mitgliedschaften', match_field: 'any', match_value: 'MITGLIEDSBEITRAG', match_type: 'contains', priority: 8 },
  { categoryKey: 'Mitgliedschaften', match_field: 'any', match_value: 'BEITRAG', match_type: 'contains', priority: 3 },
]
